# ベースイメージとしてPython 3.12.5を使用
FROM python:3.12.5

# 作業ディレクトリを設定
WORKDIR /workspaces/misskey-analysis

# install python package
COPY ./pyproject.toml* ./poetry.lock* ./
RUN pip install poetry \
    && poetry config virtualenvs.create false
RUN poetry install
